mm-CreateSBIPage
ucsb-cs156-s23/proj-courses-s23-7pm-2 pull request #12
Opened 2023-05-25 21:52 UTC by maya-maye

In this PR, I added Search By Instructor Page, story, and test. Because the search by instructor form is not up yet, the page only has its title right now.

2023-05-31 20:52 UTC, JNewman-cell requested changes

2023-05-31 20:52 UTC, JNewman-cell commented on frontend/src/App.js
change professor to instructor like Justin's PR

2023-05-31 20:52 UTC, JNewman-cell commented on frontend/src/main/pages/SearchByInstructor/SearchByInstructorPage.js
Needs to set up functions to fetch courses by instructor using the backend function in main

2023-06-03 22:23 UTC, pconrad requested changes
Please remove the commented out test.

2023-06-03 22:23 UTC, pconrad commented on frontend/src/tests/pages/SearchByInstructor/SearchByInstructorPage.test.js
> +//     const selectSubject = screen.getByLabelText("Subject Area");
Commented out tests shouldn't go into a PR intended for merging into main.

Could you remove this test?

2023-06-04 04:39 UTC, JNewman-cell approved these changes

2023-06-05 22:17 UTC, Arik commented
https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-2/pull/34 further along

2023-06-05 22:17 UTC, closed without merging